kaist-cp/kaist-cp.github.io

- _data/people.yml
- _people/jiseung.hong.md
- index.md
editing room no. and contact in index.md, people.yml.
> (Edit) room number, contact

- index.md
Signed-off-by: Kyeongmin Cho <kyeongmin.cho@kaist.ac.kr>
> index: Fix students room number

- _people/chunmyong.park.md
I have found trivial typo issue just right before, so I send PR with fixed version. Sorry for inconvenience. Thank you!
> Modify trivial typo issue in chunmyong.park.md

- _data/people.yml
- _people/siwon.kim.md
added personal information of Siwon Kim
> ADD: Siwon Kim info update

- _data/people.yml
- _includes/person_experience.md
- _people/jeongwoon.choi.md
Hello, I made my own page as described in helpdesk [link](https://github.com/kaist-cp/helpdesk#first-things-to-do).
Also I tried to make my mattermost account but it didn't work well. Can I get some help on making my mattermost account?
> Add brief explaination of Jeong Woon

- _data/people.yml
- _people/sunghwan.shim.md
> Add sunghwan.shim info

- _data/people.yml
- _people/jaemin.yu.md
> Add jaemin.yu info

- _data/people.yml
- _people/taewoo.kim.md
> Add taewoo.kim info

- _data/people.yml
- _people/seungmin.jeon.md
> Added seungmin.jeon info

- _data/people.yml
- _people/yeonwoo.nam.md
> Add info about yeonwoo.nam

- _data/people.yml
- _people/sunghwan.shim.md
정보 업데이트 (undergraduate -> master) 했습니다.
> Update sunghwan.shim info

- _projects/pmem.md
- index.md
Signed-off-by: Kyeongmin Cho <kyeongmin.cho@kaist.ac.kr>
> pmem: Add a project page for pmem

- _data/papers.yml
- _includes/publications.md
- paper: Reusable 도장 찍힌 paper에 appendix를 이어붙여서 local copy를 만들었습니다.
- artifact:
+ coq proof, model checker 링크 각각 추가했습니다.
+ 이 과정에서 artifact-copy 참조하는 로직의 수정이 있었습니다. (+ pebr의 artifact 이름을 지었습니다)
> pub: Add paper, artifacts of pldi21

- _data/people.yml
- _people/sunghyuk.kay.md
> Update sunghyuk.kay's status

- _people/chunmyong.park.md
> Update chunmyong.park info

- _data/people.yml
https://cp.kaist.ac.kr/#people 에 사진이 표시되도록 수정했습니다.
> Add jaemin.choi image

- pages/join.md
* Dooray로 바뀌면서 가상 메일을 추가하는 방법이 바뀐것에 맞다록 설명을 업데이트했습니다.
> Update instruction to add new mail address.

- pages/join.md
Port 11003 is disabled, update the corresponding info in `join` section.
> Update available port numbers.

- pages/join.md
> Remove remote desktop info from join

- _data/papers.yml
- _projects/memento.md
Signed-off-by: Kyeongmin Cho <kyeongmin.cho@kaist.ac.kr>
> Revise memento page

- _includes/person_contact.md
* Remove line break, so profile pages look good.
> fix: Remove line break

- _people/jeonghyeon.kim.md
* Fixed unnatural English expressions with ChatGPT.
* Updated the current status: `Undergraduate Intern` -> `Master's Student`.
* Applied minor fixes on Experiences and Awards.
> Update jeonghyeon's page with ChatGPT

- _data/people.yml
- _people/jaewoo.kim.md
> Update Jaewoo Kim's profile.
